### ISSUE TITLE
Please Help Rtl8812BU supports monitor mode? Packet Injection? evil-Twin Attack?

### ISSUE THREAD

**Issue by saineox** [its-izhar/rtl88x2bu-driver#1]
Please Help
Rtl8812BU supports
monitor mode?
Packet Injection?
Ad-hoc for Hostpad?
evil-Twin Attack?
Kali Linux supported or not?

**Comment by seanmmitchell** [comment]
Same issue here on Linux Mint 19. Driver installed, and runs on reboot. Issue occurs in airmon-ng when attempting to start adapter. airmon-ng says its going to rename since the name is too long for Linux and then fails to set monitor mode "Operation not supported - 95". If I jut run airmon-ng it shows ????? for driver on my wireless interface so I am wondering if this is the problem.

**Comment by its-izhar** [comment]
The sole purpose of this repo is to provide a fully functional (and by functional I mean "as is" out of the box) drivers that can compile against respective kernel versions. Please consider submitting patches for features if you think it is useful, I will review and apply it solely on my discretion.

Closing it until then.
--
Izhar
